name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    # Only label pull requests on the repo in the jenkinsci GitHub organization
    if: ${{ github.repository_owner == 'jenkinsci' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
